---
title: "Estimation de la surface par modèle linéaire à coefficients variant spatialement - Calcul du maillage SPDE"
author: "X. Freulon, N. Desassis, H. Wackernagel"
date: "31 juillet 2022"
output:
  pdf_document: default
  html_document: default
---


```{r initialisation, echo=TRUE, eval=TRUE}
library(RGeostats)
rm(list=ls())
set.seed(121122)
area_nm   <- "Rhone" # Selection de la zone dans "BPL", "Creuse", "Oise", "Rhone"
nm_input_RData <- paste0("../Data/CCR_", area_nm, ".Rdata")
nm_output_mesh <- paste0("../Data/CCR_", area_nm, "_meshCoords.ascii")


# initialisation of the graphics (saving or not in a file)
source(file = "./functions_figures.R")
gg <- fig.init(
  study.key    = paste("LMOK", "meshing", sep = "_"), 
  flag.graphic = TRUE, 
  flag.file    = TRUE, 
  type.file    = "png", 
  dir.fig      = "../figures/")

```


```{r loading_data, echo=TRUE, eval=TRUE}
load(file = nm_input_RData)
poly = dpts[[1]]$polygon
grd=db.grid.init(poly,nodes = c(50,50),margin=c(10,10))
grd = db.locate(grd,"Polygon","z")
# grd = morpho(grd,0.5,1.5,oper = "dilate",niter = 3)
grd = morpho(grd,0.5,1.5,oper = "close")
grd = morpho(grd,0.5,1.5,oper = "dilate",niter = 10)
grd = morpho(grd,0.5,1.5,oper = "erode")
grdCoarse = db.create(flag.grid = TRUE,
                      nx = grd$nx/2,
                      dx = grd$dx*2,
                      x0=grd$x0+grd$dx/2)
grdCoarse = migrate(dbin = grd, dbout = grdCoarse, radix="")
# # grdCoarse = db.grid.refine(grd,nmult=c(2,2),flag.refine = F,flag.copy = T)
grdCoarse = db.rename(grdCoarse,grdCoarse$natt,"morpho")

# Plot of the coarse grid
if(gg$start(file_name = paste0("coarse_grid_sel"), radix = "morpho")) {
  plot(grdCoarse)
  gg$end()
  }

grdCoarse = db.stat.grid(dat,grdCoarse,"x1",fun="num")
grdCoarse = db.polygon(grdCoarse,polygon = poly)

# Plot of limits and selected cells
if(gg$start(file_name = paste0("limits_sel"), radix = "morpho")) {
  plot(grdCoarse)
  plot(poly,add=T, col = "yellow")
  gg$end()
  }


```


```{r generation_vertices, echo=TRUE, eval=TRUE}
coords = NULL
lambda = .04
n = rpois(grdCoarse$nech,lambda * grdCoarse[,"Stats.rank"])
n[grdCoarse[,"Polygon"]==1] = apply(cbind(n[grdCoarse[,"Polygon"]==1],2),1,max)
n[grdCoarse[,"Polygon"]==0 & grdCoarse[,"morpho"]==1] = 1
print(sum(n))
for(i in 1:grdCoarse$nech)
{
  
  x = runif(n[i]) * grdCoarse$dx[1] + grdCoarse[i,"x1"]
  y = runif(n[i]) * grdCoarse$dx[2] + grdCoarse[i,"x2"]
  coords = rbind(coords,cbind(x,y))
  
}

# Plot of limits and selected cells
if(gg$start(file_name = paste0("points"), radix = "vertices")) {
  plot(poly,col = "yellow", main = "Vertices of the meshing")
  points(coords,cex=.1, add = TRUE)
  gg$end()
  }

```

```{r meshing, echo=TRUE, eval=TRUE}
pts  <- db.create(x1=coords[,1],x2=coords[,2])
mesh <- meshing(pts,triswitch="nqQ")
# Plot of final meshing
if(gg$start(file_name = paste0("and_limits"), radix = "meshing")) {
  plot(poly, col = "gray", main = "SPDE meshing")
  plot(mesh,lwd=0.1, add = TRUE)
  gg$end()
  }
```

```{r saving, echo=TRUE, eval=TRUE}
write.csv(coords, file = nm_output_mesh)
```

