---
  title: "Estimation de la surface par modèle linéaire à coefficients variant spatialement - Workflow LM"
  author: "X. Freulon, N. Desassis, H. Wackernagel"
  date: "12 août 2022"
  output:
    pdf_document: default
    html_document: default
---

# Initialisation

R et RGeostats

```{r R_init, echo=TRUE, eval=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(RGeostats)
library(Matrix)
rm(list=ls())
constant.define("asp",1)

```

Paramétrage 

```{r}
source(file = "./conf.R")
N <- N_adm # Nombre minimal de biens par unité géographique

# initialisation of the graphics (saving or not in a file)
source(file = "./functions_figures.R")
gg <- fig.init(
  study.key    = paste("LM", type, paste0("N",N), sep = "_"), 
  flag.graphic = TRUE, 
  flag.file    = TRUE, 
  type.file    = "png", 
  dir.fig      = "../figures/")

```

Fonctions auxiliaires

```{r}
source("functions_prepareDB.R")
source("functions_Xval.R")
```

```{r}
load(file = nm_input_RData)
dat = filter_dat(dat,filter_list)
folds <- sample(x = 1:n.fold, size = dat$nech, replace = TRUE)
```


```{r}
# Regression linéaire globale
fn_estim_LM1 = function(dbin,dbout,radix = "kfold_LM")
{
  Y = db.extract(dbin,db.getname(dbin,"z",1),flag.compress = T)
  X = as.data.frame(db.extract(dbin,db.getname(dbin,"f",NA),flag.compress = T))
  reslm = lm(Y~0+.,data=X)
  for(i in 1:ncol(X))
  {
    nm_estim <- paste(radix, paste0("Z",i), "estim", sep = ".")
    dbout = db.replace(dbout, name = nm_estim, tab = rep(reslm$coefficients[i],dbout$nactive),flag.sel = T)
  }
  
  return(dbout)
}

# Regression linéaire par unité administrative (nombre de biens > N)
fn_estim_LM2 = function(dbin,dbout,radix = "kfold_LM_admin")
{
  Y = db.extract(dbin,db.getname(dbin,"z",1),flag.compress = T)
  X = as.data.frame(db.extract(dbin,db.getname(dbin,"f",NA),flag.compress = T))
  cityTrain = db.extract(dbin,"COM_INSEE",flag.compress = T)
  cityTest = db.extract(dbout,"COM_INSEE",flag.compress = T)
  reslmGlobal = lm(Y~0+.,data=X)
  res = matrix(NA,nrow=dbout$nactive,ncol=ncol(X))
  for(i in 1:ncol(X))
  {
    res[,i] = reslmGlobal$coefficients[i]
  }
  for(i in unique(cityTrain))
  {
    ind = cityTrain==i
    if(sum(ind)>N)
    {
      x = as.data.frame(X[ind,])
      y = Y[ind]
      reslm = lm(y~0+.,data=x)
      indTest = cityTest == i
      for(j in 1:ncol(x))
      {
        res[indTest,j] = reslm$coefficients[j]
      }
    }
  }
  
  for(i in 1:ncol(X))
  {
    nm_estim <- paste(radix, paste0("Z",i), "estim", sep = ".")
    dbout = db.replace(dbout, name = nm_estim, tab = res[,i],flag.sel = T)
  }
  
  return(dbout)
}
```

# Régression linéaire globale

```{r LM_global}
datXval <- prepareDb(dat,nm_fac,nm_var,nm_sel,nm_type,type)
datXval <- db.add(datXval, folds,locnames = "code")
datXval <- kfold_compute(datXval, fn_estim = fn_estim_LM1, radix = "kfold_LM1", 
                         verbose = FALSE)

# k-fold results by folds AND graphics 
tab <- kfold_results(datXval, name_real = nm_var, name_esti = "kfold_LM1.S.estim", 
            stats = c("number", "min", "max", "mean", "MAE", "RMSE"), 
            flag.fig = TRUE, plot_fn = gg)
knitr::kable(round(tab,2), caption = paste0("Validation croisée par K-fold (K=", n.fold,")"))

# k-fold results by type
datXval <- db.locate(datXval, names = nm_type, loctype = "code", flag.locnew = TRUE)
tab <- kfold_results(datXval, name_real = nm_var, name_esti = "kfold_LM1.S.estim", 
                     stats = c("number", "min", "max", "mean", "MAE", "RMSE"),
                     flag.fig = FALSE, plot_fn = NA)
knitr::kable(round(tab,2), caption = paste0("Validation croisée par K-fold (K=", n.fold,")"))
```

# Régression linéaire par unité administrative


```{r LM_CODE_INSEE}
datXval <- prepareDb(dat,nm_fac,nm_var,nm_sel,nm_type,type)
datXval <- db.add(datXval, folds,locnames = "code")
datXval <- kfold_compute(datXval, fn_estim = fn_estim_LM2, radix = "kfold_LM2", 
                         verbose = FALSE)
tab <- kfold_results(datXval, name_real = nm_var, name_esti = "kfold_LM2.S.estim", 
                     stats = c("number", "min", "max", "mean", "MAE", "RMSE"),
                     flag.fig = TRUE, plot_fn = gg)
knitr::kable(round(tab,2), caption = paste0("Validation croisée par K-fold (K=", n.fold,")"))

datXval <- db.locate(datXval, names = nm_type, loctype = "code", flag.locnew = TRUE)
tab <- kfold_results(datXval, name_real = nm_var, name_esti = "kfold_LM2.S.estim", 
                     stats = c("number", "min", "max", "mean", "MAE", "RMSE"),
                     flag.fig = FALSE, plot_fn = NA)
knitr::kable(round(tab,2), caption = paste0("Validation croisée par K-fold (K=", n.fold,")"))
```

# Calcul de la vraisemblance

## Régression globale

```{r ll_global}
computeLogLike = function(dbin)
{
  Y = db.extract(dbin,db.getname(dbin,"z",1),flag.compress = T)
  X = as.data.frame(db.extract(dbin,db.getname(dbin,"f",NA),flag.compress = T))
  reslm = lm(Y~0+.,data=X)
  res = resid(reslm)
  vres = mean(res^2) - mean(res)^2
  return(length(res) * log(vres) + sum(res^2)/vres)
}


datXval = prepareDb(dat,nm_fac,nm_var,nm_sel,nm_type,"flat")

l1 = computeLogLike(datXval)

datXval = prepareDb(dat,nm_fac,nm_var,nm_sel,nm_type,"house")

l2 = computeLogLike(datXval)

(-l1-l2)/2
```

## Régression par unité administrative

```{r ll_local}
computeLogLike = function(dbin)
{
  Y = db.extract(dbin,db.getname(dbin,"z",1),flag.compress = T)
  X = as.data.frame(db.extract(dbin,db.getname(dbin,"f",NA),flag.compress = T))
  
  
  city = db.extract(dbin,"COM_INSEE",flag.compress = T)
  reslmGlobal = lm(Y~0+.,data=X)
  resGlobal = resid(reslmGlobal)
  vresGlobal = mean(resGlobal^2) - mean(resGlobal)^2
  l = 0
  for(i in unique(city))
  {
    ind = city==i
    x = as.data.frame(X[ind,])
    y = Y[ind]
    if(sum(ind)>N)
    {
      reslm = lm(y~0+.,data=x)
      res = resid(reslm)
      vres = mean(res^2) - mean(res)^2
      l = l + length(res) * log(vres) + sum(res^2)/vres
    }    else
    {
      l = l + length(y) * log(vresGlobal) + sum(resGlobal[ind]^2)/vresGlobal
    }
  }
    return(l)
}


datXval = prepareDb(dat,nm_fac,nm_var,nm_sel,nm_type,"flat")

l1 = computeLogLike(datXval)

datXval = prepareDb(dat,nm_fac,nm_var,nm_sel,nm_type,"house")

l2 = computeLogLike(datXval)

(-l1-l2)/2
```
