---
title: "makeMesh.Rmd"
output: html_document
---

```{r}
library(RGeostats)
rm(list=ls())
set.seed(121122)
```


```{r}
load(file = "../Data/CCR_69.Rdata")
poly = dpts[[1]]$polygon
grd=db.grid.init(poly,nodes = c(50,50),margin=c(10,10))
grd = db.locate(grd,"Polygon","z")
#grd = morpho(grd,0.5,1.5,oper = "dilate",niter = 3)
grd = morpho(grd,0.5,1.5,oper = "close")
grd = morpho(grd,0.5,1.5,oper = "dilate",niter = 10)
grd = morpho(grd,0.5,1.5,oper = "erode")
grdCoarse = db.grid.refine(grd,nmult=c(2,2),flag.refine = F,flag.copy = T)
grdCoarse = db.rename(grdCoarse,grdCoarse$natt,"morpho")
plot(grdCoarse)

grdCoarse = db.stat.grid(dat,grdCoarse,"x1",fun="num")
plot(poly,add=T)
```


```{r}
coords = NULL
lambda = .04
n = rpois(grdCoarse$nech,lambda * grdCoarse[,"Stats.rank"])
n[grdCoarse[,"Polygon"]==1] = apply(cbind(n[grdCoarse[,"Polygon"]==1],2),1,max)
n[grdCoarse[,"Polygon"]==0 & grdCoarse[,"morpho"]==1] = 1
print(sum(n))
for(i in 1:grdCoarse$nech)
{
  
  x = runif(n[i]) * grdCoarse$dx[1] + grdCoarse[i,"x1"]
  y = runif(n[i]) * grdCoarse$dx[2] + grdCoarse[i,"x2"]
  coords = rbind(coords,cbind(x,y))
  
}
plot(coords,cex=.1)
```

```{r}
pts = db.create(x1=coords[,1],x2=coords[,2])
mesh = meshing(pts,triswitch="nqQ")
plot(mesh,lwd=0.1)
#plot(poly,add=F)
A=mesh.barycenter(dat,mesh)
#plot(dat,add=T,cex=.1,name.post=1)
```

```{r}
write.csv(coords,"meshCoords.ascii")
```

